# Generated by Django 3.2 on 2022-05-03 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tutorial', '0003_auto_20220402_0149'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.CharField(choices=[('Primary 1', 'Primary 1'), ('Primary 2', 'Primary 2'), ('Primary 3', 'Primary 3'), ('Primary 4', 'Primary 4'), ('Primary 5', 'Primary 5'), ('Primary 6', 'Primary 6'), ('JSS1', 'JSS1'), ('JSS2', 'JSS2'), ('JSS3', 'JSS3'), ('SS1', 'SS1'), ('SS2', 'SS2'), ('SS3', 'SS3')], default=False, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referenceCode', models.CharField(blank=True, default='', max_length=100)),
                ('paystackAccessCode', models.CharField(blank=True, default='', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('duration', models.PositiveBigIntegerField(default=30)),
                ('paymentFor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tutorial.tutormodel')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjects', models.CharField(choices=[('english language', 'English Language'), ('general mathematics', 'General Mathematics'), ('agricultural science', 'Agricultural Science'), ('further mathematics', 'Further Mathematics'), ('basic mathematics', 'Basic Mathematics'), ('verbal reasoning', 'Verbal Reasoning'), ('quantitative reasoning', 'Quantitative Reasoning'), ('business studies', 'Business Studies'), ('basic technology', 'Basic Technology'), ('basic sciences', 'Basic Sciences'), ('geography', 'Geography'), ('technical Drawing', 'Technical Drawing'), ('commerce', 'Commerce'), ('accounting', 'Accounting'), ('history', 'History'), ('fine art', 'Fine Art'), ('computer science', 'ICT - Computer Science'), ('french', 'French'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('commerce', 'Commerce'), ('literature in english', 'Literature in English'), ('office practice', 'Office practice'), ('government', 'Government'), ('economics', 'Economics')], default=False, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires_in', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('subscriber', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='account.payment')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.IntegerField()),
                ('address', models.CharField(default=False, max_length=500)),
                ('profilepix', models.FileField(default=0, upload_to='')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gettutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Start', models.DateField(auto_created=True)),
                ('kidsnum', models.CharField(max_length=50)),
                ('modeoftutor', models.CharField(choices=[('Not Sure', 'Not Sure'), ('Online', 'Online'), ('Physical', 'Physical')], default='Not Sure', max_length=20)),
                ('goalofchild', models.CharField(choices=[('Special need support', 'Special need support'), ('Help with assignment', 'Help with assignment'), ('Home schooling', 'Home schooling'), ('School work', 'School work'), ('Improve grades', 'Improve grades'), ('Prepare for school test', 'Prepare for school test'), ('ACT exams preparation', 'ACT exams preparation'), ('SAT exams preparation', 'SAT exams preparation'), ('UTME/JAMB preparation', 'UTME/JAMB preparation'), ('SSCE/NECO/GCE preparation', 'SSCE/NECO/GCE preparation'), ('IGCSE preparation', 'IGCSE preparation')], max_length=100)),
                ('briefbio', models.TextField(max_length=3000)),
                ('curiculum', models.CharField(choices=[('Curiculum', 'Curiculum'), ('Nigerian', 'Nigerian'), ('British', 'British'), ('American', 'American'), ('IPC', 'IPC')], default='Not Sure', max_length=100)),
                ('typeoftutor', models.CharField(choices=[('Not Sure', 'Not Sure'), ('M', 'Male'), ('F', 'Female')], default='Not Sure', max_length=20)),
                ('address', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=14)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('hrsperday', models.CharField(choices=[('Not Sure', 'Not Sure'), ('1hr', '1hr'), ('2hrs', '2hrs'), ('3hrs', '3hrs'), ('4hrs', '4hrs'), ('5hrs', '5hrs')], default='Not Sure', max_length=10)),
                ('starttime', models.CharField(choices=[('Not Sure', 'Not Sure'), ('8AM', '8AM'), ('9AM', '9AM'), ('10AM', '10AM'), ('11AM', '11AM'), ('12AM', '12AM'), ('1PM', '1PM'), ('2PM', '2PM'), ('3PM', '3PM'), ('4PM', '4PM'), ('5PM', '5PM'), ('6PM', '6PM')], default='Not Sure', max_length=500)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('duration', models.PositiveBigIntegerField(choices=[(1, '1 Day'), (7, '1 Week'), (30, '1 Month'), (90, '3 Months'), (180, '6 Months')], default=1)),
                ('classofkid', models.ManyToManyField(to='account.Class')),
                ('subjects', models.ManyToManyField(to='account.Subject')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Activetutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('expires_in', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('turorialkey', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='account.gettutor')),
            ],
        ),
    ]
