# Generated by Django 3.2 on 2022-05-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_gettutor_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gettutor',
            name='Start',
            field=models.DateField(auto_created=True),
        ),
    ]
