# Generated by Django 3.2 on 2022-05-04 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_alter_gettutor_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjects', models.CharField(default=False, max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='activetutor',
            name='expires_in',
            field=models.DateField(auto_created=True, null=True),
        ),
        migrations.CreateModel(
            name='Workhistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(auto_created=True)),
                ('organization', models.CharField(default=False, max_length=300)),
                ('country', models.CharField(default=False, max_length=300)),
                ('roll', models.CharField(default=False, max_length=300)),
                ('active', models.BooleanField()),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Educationalhistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end', models.DateField(auto_created=True)),
                ('start', models.DateField(auto_created=True)),
                ('school', models.CharField(default=False, max_length=800)),
                ('country', models.CharField(default=False, max_length=300)),
                ('course', models.CharField(default=False, max_length=500)),
                ('degrees', models.CharField(default=False, max_length=500)),
                ('grade', models.CharField(default=False, max_length=300)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Becometutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(auto_created=True)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.IntegerField()),
                ('whatsappnumber', models.IntegerField()),
                ('sex', models.CharField(choices=[('Not Sure', 'Not Sure'), ('M', 'Male'), ('F', 'Female')], default='Not Sure', max_length=20)),
                ('address', models.CharField(default=False, max_length=500)),
                ('primarylanguage', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('educational', models.ManyToManyField(to='account.Educationalhistory')),
                ('subjects', models.ManyToManyField(to='account.Subject')),
                ('teachinglocations', models.ManyToManyField(to='account.Location')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workhistory', models.ManyToManyField(to='account.Workhistory')),
            ],
        ),
    ]
