# Generated by Django 3.2 on 2022-05-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_subjects_location_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='becometutor',
            name='address',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='class',
            name='classes',
            field=models.CharField(choices=[('Primary 1', 'Primary 1'), ('Primary 2', 'Primary 2'), ('Primary 3', 'Primary 3'), ('Primary 4', 'Primary 4'), ('Primary 5', 'Primary 5'), ('Primary 6', 'Primary 6'), ('JSS1', 'JSS1'), ('JSS2', 'JSS2'), ('JSS3', 'JSS3'), ('SS1', 'SS1'), ('SS2', 'SS2'), ('SS3', 'SS3')], max_length=100),
        ),
        migrations.AlterField(
            model_name='educationalhistory',
            name='country',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='educationalhistory',
            name='course',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='educationalhistory',
            name='degrees',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='educationalhistory',
            name='grade',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='educationalhistory',
            name='school',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='gettutor',
            name='address',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subjects',
            field=models.CharField(choices=[('english language', 'English Language'), ('general mathematics', 'General Mathematics'), ('agricultural science', 'Agricultural Science'), ('further mathematics', 'Further Mathematics'), ('basic mathematics', 'Basic Mathematics'), ('verbal reasoning', 'Verbal Reasoning'), ('quantitative reasoning', 'Quantitative Reasoning'), ('business studies', 'Business Studies'), ('basic technology', 'Basic Technology'), ('basic sciences', 'Basic Sciences'), ('geography', 'Geography'), ('technical Drawing', 'Technical Drawing'), ('commerce', 'Commerce'), ('accounting', 'Accounting'), ('history', 'History'), ('fine art', 'Fine Art'), ('computer science', 'ICT - Computer Science'), ('french', 'French'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('commerce', 'Commerce'), ('literature in english', 'Literature in English'), ('office practice', 'Office practice'), ('government', 'Government'), ('economics', 'Economics')], max_length=300),
        ),
        migrations.AlterField(
            model_name='workhistory',
            name='country',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='workhistory',
            name='organization',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='workhistory',
            name='roll',
            field=models.CharField(max_length=300),
        ),
    ]
