# Generated by Django 3.2 on 2022-05-04 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20220504_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='becometutor',
            name='educational',
        ),
        migrations.RemoveField(
            model_name='becometutor',
            name='workhistory',
        ),
        migrations.AlterField(
            model_name='educationalhistory',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='account.becometutor'),
        ),
        migrations.AlterField(
            model_name='workhistory',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='account.becometutor'),
        ),
    ]
