# Generated by Django 3.2 on 2022-05-04 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20220504_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educationalhistory',
            old_name='user',
            new_name='tutor',
        ),
        migrations.RenameField(
            model_name='workhistory',
            old_name='user',
            new_name='tutor',
        ),
    ]
