# Generated by Django 3.2 on 2022-03-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='documents/')),
                ('publisheddate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-publisheddate',),
            },
        ),
        migrations.DeleteModel(
            name='AudioPost',
        ),
        migrations.DeleteModel(
            name='VideoPost',
        ),
    ]
