# Generated by Django 3.2 on 2022-04-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_auto_20220321_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutormodel',
            name='subjects',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutormodel',
            name='location',
            field=models.CharField(max_length=16),
        ),
    ]
