# Generated by Django 3.2 on 2022-03-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedPostVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=1000)),
                ('video', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('publisheddate', models.DateTimeField(auto_now_add=True)),
                ('updateddate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-publisheddate',),
            },
        ),
        migrations.RemoveField(
            model_name='feedpost',
            name='video',
        ),
    ]
