# Generated by Django 3.2 on 2022-03-20 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('publisheddate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-publisheddate',),
            },
        ),
        migrations.CreateModel(
            name='Syllable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Syllable', models.CharField(max_length=1000)),
                ('publisheddate', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllable.subjects')),
            ],
            options={
                'ordering': ('-publisheddate',),
            },
        ),
    ]
